# config for phase 1 & 2

dataset:
  name: bdd100k
  # raw BDD100K
  raw_dir: data/raw/bdd100k
  # processed splits
  processed_dir: data/processed
  # image subdir
  images_subdir: images/100k

  # DSDL annotations
  dsdl_dir: data/BDD100K/dsdl/det_full/dsdl_Det_full
  train_samples: set-train/train_samples.json
  val_samples: set-val/val_samples.json

  # Weather categories for splitting
  clean_weather:
    - clear
    - sunny
    - partly cloudy
    - overcast
  adverse_weather:
    - foggy
    - rainy
    - snowy

  # class mapping
  class_mapping:
    person: 0
    rider: 0
    car: 2
    truck: 7
    bus: 5
    train: 6
    motor: 3
    bike: 1

  class_names:
    0: person
    1: bicycle
    2: car
    3: motorcycle
    5: bus
    6: train
    7: truck

model:
  weights: yolov8m.pt
  imgsz: 640
  conf_threshold: 0.25
  iou_threshold: 0.45
  device: cuda:0
  batch_size: 16

evaluation:
  iou_threshold: 0.5
  max_det: 100
seed: 7
output_dir: outputs/phase1
# phase 2
phase2_output_dir: outputs/phase2

preprocessing:
  msrcr:
    sigma_list: [15, 80, 250]
    alpha: 125.0
    beta: 46.0
  clahe:
    clip_limit: 2.0
    tile_grid_size: [8, 8]
